
[functions.auth-2fa]
enabled = true
verify_jwt = false
import_map = "./functions/auth-2fa/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/auth-2fa/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/auth-2fa/*.html" ]

[functions.mercadopago]
enabled = true
verify_jwt = false
entrypoint = "./functions/mercadopago/index.ts"

[functions.robots]
enabled = true
verify_jwt = false
entrypoint = "./functions/robots/index.ts"

[functions.sitemap]
enabled = true
verify_jwt = false
entrypoint = "./functions/sitemap/index.ts"
